import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NotificationContextProvider } from "@/store/notification-context";
import MainHeader from "@/components/layout/main-header";
import Notification from "@/components/notification/notification";
import NotificationContainer from "../components/notification/notification-container";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NotificationContextProvider>
          <MainHeader />
          <main>{children}</main>
          <NotificationContainer />
        </NotificationContextProvider>
      </body>
    </html>
  );
}
